### ISSUE TITLE
field__in查询存在问题

### ISSUE THREAD

**Issue by lgcshy** [tx7do/go-utils#1]
req.query 查询id in [1,2,3] 或者{"name__in" : ["tom", "jimmy"]}

报错：
json: cannot unmarshal object into Go value of type []map[string]string

**Comment by tx7do** [comment]
确实，我来修复一下。

**Comment by tx7do** [comment]
是这样的，实际上我value是上传的string，然后，由我自己自行解析。我的文档有误，应该是这样写的：

```json
{"name__in" : "[\"tom\", \"jimmy\"]"}
```
